In [1]:
import numpy as np


# Scalar Vector operations

In [2]:
a = np.array([4,1,2,3])
a

array([4, 1, 2, 3])

In [3]:
2 * a

array([8, 2, 4, 6])

In [4]:
2 + a

array([6, 3, 4, 5])

In [5]:
a%2

array([0, 1, 0, 1])

# Vector Vector operations

## Addition

In [7]:
v = np.array([1,2,3])
u = np.array([1,2,3,4])
v * u
# Any vector-vector operations work only if the shapes of the vectors match.

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

## Multiplication

In [12]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    result = np.zeros(U.shape[0])
    for i in range(U.shape[0]):
        result[i] = U[i].dot(v)

    return result

U = np.array([[2,4,5,6],
              [1,2,1,2],
              [3,1,2,1]])
v = np.array([1,0.5,2,1])

w = matrix_vector_multiplication(U,v)

In [13]:
w

array([20. ,  6. ,  8.5])

In [14]:
x = U.dot(v)
x

array([20. ,  6. ,  8.5])

In [25]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    result = np.zeros((U.shape[0],V.shape[1]))
    
    for i in range(V.shape[1]):
        vi = V[:, i]
        result[:, i] = matrix_vector_multiplication(U,vi)
            
    return result

U = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
V = np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])

W = matrix_matrix_multiplication(U,V)
W

array([[ 30.,  36.,  42.],
       [ 66.,  81.,  96.],
       [102., 126., 150.]])

In [26]:
X = U.dot(V)
X

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])