In [7]:
import numpy as np
import pandas as pd
import os

In [10]:
print(os.getcwd())

/home/dheerajmachiraju/notebooks


In [11]:
file_path = '/home/dheerajmachiraju/housing.csv'

In [12]:
df = pd.read_csv(file_path)

In [38]:
df.head(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   
5    -122.25     37.85                52.0        919.0           213.0   
6    -122.25     37.84                52.0       2535.0           489.0   
7    -122.25     37.84                52.0       3104.0           687.0   
8    -122.26     37.84                42.0       2555.0           665.0   
9    -122.25     37.84                52.0       3549.0           707.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY  
5       413.0       193.0         4.0368            269700.0        NEAR BAY  
6      1094.0       514.0         3.6591            299200.0        NEAR BAY  
7      1157.0       647.0         3.1200            241400.0        NEAR BAY  
8      1206.0       595.0         2.0804            226700.0        NEAR BAY  
9      1551.0       714.0         3.6912            261100.0        NEAR BAY

In [17]:
print(f"The dataframe has {df.shape[1]} columns")

The dataframe has 10 columns


In [27]:
df.columns[df.isnull().sum() > 1]

Index(['total_bedrooms'], dtype='object')

In [24]:
print(f"The column with missing values is {df.columns[df.isnull().sum() > 1]}")

The column with missing values is Index(['total_bedrooms'], dtype='object')


In [28]:
df['ocean_proximity'].nunique()

5

In [30]:
df[df['ocean_proximity'] == 'NEAR BAY']['median_house_value'].mean().round(2)

259212.31

In [37]:
mean_total_bedrooms = df['total_bedrooms'].mean()
mean_total_bedrooms

537.8705525375617

In [34]:
df['total_bedrooms'] = df['total_bedrooms'].fillna(mean_total_bedrooms)

In [35]:
df['total_bedrooms'].isnull().sum()

0

In [36]:
new_mean_total_bedrooms = df['total_bedrooms'].mean()
new_mean_total_bedrooms

537.8705525375617

In [39]:
df['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [59]:
X = df[df['ocean_proximity'] == 'ISLAND'][['housing_median_age','total_rooms','total_bedrooms']].values
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [60]:
XTX = (X.T).dot(X)

In [61]:
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [62]:
inv_XTX = np.linalg.inv(XTX)

In [63]:
y = np.array([950, 1300, 800, 1000, 1300])

In [65]:
temp = inv_XTX.dot(X.T)
w = temp.dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])